---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wgacoec4/public_html/
    - /bin/cp -R content $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R HTWF $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp skin.css $DEPLOYPATH
